/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 assembly_step.glb -T -S
Files: assembly_step.glb [12.65MB] > assembly_step-transformed.glb [567.36KB] (96%)
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { useStepStore } from '@/store/useStepStore'
import * as THREE from 'three'

export default function Model(props) {
  const { currentStep } = useStepStore(state => state)
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assembly_action-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log('___actions', actions)
    switch (currentStep) {
      case 2:
        actions.Action_1.setLoop(THREE.LoopOnce);
        actions?.Action_1.play()
        break
      case 3:
        actions.Action_2.setLoop(THREE.LoopOnce);
        actions?.Action_2.play()
        break
    }
  }, [actions, currentStep])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="parts">
        <group name="Armature" position={[0, 0.053, 0]}>
          <group name="BoneStep_1" rotation={[Math.PI, -1.571, 0]} visible={currentStep >= 1}>
            <group name="Step_1" rotation={[-Math.PI, 1.571, 0]}>
              <mesh
                name="imagetostl_mesh0027"
                castShadow
                receiveShadow
                geometry={nodes.imagetostl_mesh0027.geometry}
                material={materials['RoughPlastic.002']}
              />
              <mesh
                name="imagetostl_mesh0027_1"
                castShadow
                receiveShadow
                geometry={nodes.imagetostl_mesh0027_1.geometry}
                material={materials.PaletteMaterial004}
              />
            </group>
          </group>
          <group name="BoneStep_2" visible={currentStep >= 2}>
            <mesh
              name="Step_2"
              castShadow
              receiveShadow
              geometry={nodes.Step_2.geometry}
              material={materials['RoughPlastic.002']}
              position={[0.001, 0.009, 0]}
            />
          </group>
          <group name="BoneStep_3" position={[0, 0.572, 0]} visible={currentStep >= 3}>
            <group name="Step_3" position={[0, 0.039, 0]}>
              <mesh
                name="imagetostl_mesh0028"
                castShadow
                receiveShadow
                geometry={nodes.imagetostl_mesh0028.geometry}
                material={materials.PaletteMaterial001}
              />
              <mesh
                name="imagetostl_mesh0028_1"
                castShadow
                receiveShadow
                geometry={nodes.imagetostl_mesh0028_1.geometry}
                material={materials.PaletteMaterial003}
              />
              <mesh
                name="imagetostl_mesh0028_2"
                castShadow
                receiveShadow
                geometry={nodes.imagetostl_mesh0028_2.geometry}
                material={materials['RoughPlastic.002']}
              />
              <mesh
                name="imagetostl_mesh0028_3"
                castShadow
                receiveShadow
                geometry={nodes.imagetostl_mesh0028_3.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assembly_bone_2.glb')
